version: '2'
services:
  frontend:
    image: 76838ac1bcda
    depends_on:
      - mongo
    environment:
      STORAGE_HOST: mongo
      HOST: 0.0.0.0
      PORT: 80
    ports:
      - "80:80"

  detector:
    image: dimorinny/twitch-interesting-fragments-detector
    depends_on:
      - mongo
      - uploader
    environment:
      NICKNAME: ${NICKNAME}
      OAUTH: ${CHAT_OAUTH}
      CHANNEL: ${CHANNEL}
      UPLOADER_HOST: uploader
      UPLOADER_PORT: 80
      STORAGE_HOST: mongo

  uploader:
    image: dimorinny/twitch-fragment-uploader
    environment:
      TWITCH_OAUTH: ${OAUTH}
      TWITCH_CHANNEL: ${CHANNEL}
      PORT: 80

  mongo:
    image: mongo:latest