version: '2'
services:
  detector:
    image: dimorinny/twitch-interesting-fragments-detector
    restart: always
    depends_on:
      - uploader
    environment:
      NICKNAME: ${NICKNAME}
      OAUTH: ${CHAT_OAUTH}
      CHANNEL: cahchec
      SPIKE_RATE: 3.5
      RECORD_DELAY: 15
      UPLOADER_HOST: uploader
      UPLOADER_PORT: 80

  uploader:
    image: dimorinny/twitch-fragment-uploader
    restart: always
    environment:
      TWITCH_OAUTH: ${OAUTH}
      UPLOAD_BACKEND: streamable
      STREAMABLE_USER: ${STREAMABLE_USER}
      STREAMABLE_PASSWORD: ${STREAMABLE_PASSWORD}
      TIMEZONE: Europe/Moscow
      TWITCH_CHANNEL: cahchec
      PORT: 80

  lena_detector:
    image: dimorinny/twitch-interesting-fragments-detector
    restart: always
    depends_on:
      - uploader
    environment:
      NICKNAME: ${NICKNAME}
      OAUTH: ${CHAT_OAUTH}
      CHANNEL: lenagol0vach
      SPIKE_RATE: 4.5
      RECORD_DELAY: 15
      UPLOADER_HOST: lena_uploader
      UPLOADER_PORT: 80

  lena_uploader:
    image: dimorinny/twitch-fragment-uploader
    restart: always
    environment:
      TWITCH_OAUTH: ${OAUTH}
      UPLOAD_BACKEND: streamable
      STREAMABLE_USER: ${STREAMABLE_USER}
      STREAMABLE_PASSWORD: ${STREAMABLE_PASSWORD}
      TIMEZONE: Europe/Moscow
      TWITCH_CHANNEL: lenagol0vach
      PORT: 80
