version: '2'
services:
  frontend:
    image: dimorinny/twitch-interesting-fragments-frontend
    restart: always
    depends_on:
      - mongo
    environment:
      STORAGE_HOST: mongo
      HOST: 0.0.0.0
      PORT: 80
    ports:
      - "80:80"

  detector:
    image: dimorinny/twitch-interesting-fragments-detector
    restart: always
    depends_on:
      - mongo
      - uploader
    environment:
      NICKNAME: ${NICKNAME}
      OAUTH: ${CHAT_OAUTH}
      CHANNEL: cahchec
      SPIKE_RATE: 3.7
      RECORD_DELAY: 25
      UPLOADER_HOST: uploader
      UPLOADER_PORT: 80
      STORAGE_TYPE: mongo
      STORAGE_HOST: mongo

  uploader:
    image: dimorinny/twitch-fragment-uploader
    restart: always
    environment:
      TWITCH_OAUTH: ${OAUTH}
      VK_OAUTH: ${VK_OAUTH}
      VK_GROUP_ID: ${VK_GROUP_ID}
      TIMEZONE: Europe/Moscow
      TWITCH_CHANNEL: cahchec
      PORT: 80

  lena_detector:
    image: dimorinny/twitch-interesting-fragments-detector
    restart: always
    depends_on:
      - mongo
      - uploader
    environment:
      NICKNAME: ${NICKNAME}
      OAUTH: ${CHAT_OAUTH}
      CHANNEL: lenagol0vach
      SPIKE_RATE: 3.7
      RECORD_DELAY: 25
      UPLOADER_HOST: lena_uploader
      UPLOADER_PORT: 80
      STORAGE_TYPE: mongo
      STORAGE_HOST: mongo

  lena_uploader:
    image: dimorinny/twitch-fragment-uploader
    restart: always
    environment:
      TWITCH_OAUTH: ${OAUTH}
      VK_OAUTH: ${VK_OAUTH}
      VK_GROUP_ID: ${VK_GROUP_ID}
      TIMEZONE: Europe/Moscow
      TWITCH_CHANNEL: lenagol0vach
      PORT: 80

  mongo:
    image: mongo:latest
    volumes:
      - /db:/data/db
