version: '2'
services:
  frontend:
    image: dimorinny/twitch-interesting-fragments-frontend
    restart: always
    depends_on:
      - mongo
    environment:
      STORAGE_HOST: mongo
      HOST: 0.0.0.0
      PORT: 8080
    ports:
      - "8080:8080"

  detector:
    image: dimorinny/twitch-interesting-fragments-detector
    restart: always
    depends_on:
      - mongo
      - uploader
    environment:
      NICKNAME: ${NICKNAME}
      OAUTH: ${CHAT_OAUTH}
      CHANNEL: ${CHANNEL}
      RECORD_DELAY: 35
      UPLOADER_HOST: uploader
      UPLOADER_PORT: 80
      STORAGE_HOST: mongo

  uploader:
    image: dimorinny/twitch-fragment-uploader
    restart: always
    environment:
      TWITCH_OAUTH: ${OAUTH}
      TWITCH_CHANNEL: ${CHANNEL}
      PORT: 80

  mongo:
    image: mongo:latest
